<!-- Display patient list page -->
<section class="container fluid">
      <h2 class="text-center py-3">Liste des patients enregistrés</h2>
      <table class="table table-striped table-hover">
            <thead>
                  <tr>
                        <th scope="col">#</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Date de naissance</th>
                        <th scope="col">Téléphone</th>
                        <th scope="col">Email</th>
                        <th scope="col">
                              <div class="d-flex">
                                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="keywords">
                                    <button class="btn btn-outline-primary" type="submit">Rechercher</button>
                              </div>
                        </th>
                  </tr>
            </thead>
            <tbody>
            <?php foreach($patients as $patient): ?>
                  <tr>
                        <td><?= $patient['id']?></td>
                        <td><?= $patient['firstname']?></td>
                        <td><?= $patient['lastname']?></td>
                        <td><?= $patient['birthdate']?></td>
                        <td><?= $patient['phone']?></td>
                        <td><?= $patient['mail']?></td>
                        <td>
                              <a class="px-3" href="profilePatient.php?id=<?= $patient['id'];?>"><i class="bi bi-person-circle"></i></a>
                              <a class="px-3" href="deletePatient.php?id=<?= $patient['id'];?>"><i class="bi bi-trash"></i></a>
                        </td>
                  </tr>
            <?php endforeach; ?>
            </tbody>
      </table>
      <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                  <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                  </li>
                  <li class="page-item active">
                        <a class="page-link" href="#">1</a>
                  </li>
                  <li class="page-item">
                        <a class="page-link" href="#">2</a>
                  </li>
                  <li class="page-item">
                        <a class="page-link" href="#">3</a>
                  </li>
                  <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                  </li>
            </ul>
      </nav>
      <div class="d-flex justify-content-center">
            <button class="btn btn-primary">
                  <a href="addPatient.php"><i class="bi bi-plus-square text-light fs-2"></i></a>
            </button>
      </div>
</section>