<!-- Display rdv list data -->
<section class="container fluid">
      <h2 class="text-center py-3">Liste des rendez-vous enregistrés</h2>
      <table class="table table-striped table-hover">
            <thead>
                  <tr>
                        <th scope="col">#</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Nom</th>
                  </tr>
            </thead>
            <tbody>
            <?php foreach($appointments as $appointment): ?>
                  <tr>
                        <td><?= $appointment['id']?></td>
                        <td><?= $appointment['firstname']?></td>
                        <td><?= $appointment['lastname']?></td>
                        <td>
                              <a href="rdv.php?id=<?= $appointment['id'];?>"><i class="bi bi-eye"></i></a>
                        </td>
                        <td>
                              <a href="deleteRdv.php?id=<?= $appointment['id'];?>"><i class="bi bi-trash"></i></a>
                        </td>
                  </tr>
            <?php endforeach; ?>
            </tbody>
      </table>
      <div class="d-flex justify-content-center">
            <button class="btn btn-primary">
                  <a href="addRdv.php"><i class="bi bi-plus-square text-light fs-2"></i></a>
            </button>
      </div>
</section>