<!-- Display patient personal data -->
<section class="container fluid">
      <h2 class="text-center py-3"><?= $patient['firstname'].' '.$patient['lastname']?></h2>
      <table class="table table-striped table-hover">
            <thead>
                  <tr>
                        <th scope="col">#</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Date de naissance</th>
                        <th scope="col">Téléphone</th>
                        <th scope="col">Email</th>
                  </tr>
            </thead>
            <tbody>
                  <tr>
                        <td><?= $patient['id']?></td>
                        <td><?= $patient['firstname']?></td>
                        <td><?= $patient['lastname']?></td>
                        <td><?= $patient['birthdate']?></td>
                        <td><?= $patient['phone']?></td>
                        <td><?= $patient['mail']?></td>
                        <td>
                              <a href="updatePatient.php?id=<?= $patient['id'];?>"><i class="bi bi-pencil-square"></i></a>
                        </td>
                  </tr>
            </tbody>
      </table>

      <!-- RDV list from patient -->
      <h2 class="text-center py-3">Liste de vos rendez-vous</h2>
      <table class="table table-striped table-hover">
            <thead>
                  <tr>
                        <th scope="col">#</th>
                        <th scope="col">Date</th>
                  </tr>
            </thead>
            <tbody>
                  <?php foreach($appointments as $appointment): ?>
                  <tr>
                        <td><?= $appointment['rdv_id']?></td>
                        <td><?= $appointment['dateHour']?></td>
                        <td>
                              <a href="rdv.php?id=<?= $appointment['rdv_id'];?>"><i class="bi bi-eye"></i></a>
                        </td>
                  </tr>
                  <?php endforeach ?>
            </tbody>
      </table>
</section>