<!-- Display rdv information page -->
<section class="container fluid">
      <h2 class="text-center py-3">Rendez-vous enregistré</h2>
      <table class="table table-striped table-hover">
            <thead>
                  <tr>
                        <th scope="col">Date</th>
                  </tr>
            </thead>
            <tbody>
                  <tr>
                        <td><?= $appointment['dateHour']?></td>
                        <td>
                              <a href="updateRdv.php?id=<?= $appointment['id'];?>"><i class="bi bi-pencil-square"></i></a>
                        </td>
                  </tr>
            </tbody>
      </table>
      <div class="d-flex justify-content-center">
            <button class="btn btn-primary">
                  <a href="addRdv.php"><i class="bi bi-plus-square text-light fs-2"></i></a>
            </button>
      </div>
</section>